'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DaneLekarza
    Public Property NrGabinetu As Integer
    Public Property Imie As String
    Public Property Nazwisko As String
    Public Property NrLekarza As Nullable(Of Integer)
    Public Property Nazwa As String
    Public Property Kod As String
    Public Property Miasto As String
    Public Property Adres As String
    Public Property Telefon As String
    Public Property Komorka As String
    Public Property NIP As String
    Public Property Bank As String
    Public Property NrKonta As String
    Public Property ZakonczonoDane As Nullable(Of Date)
    Public Property NIPlekarza As String

End Class
