'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class medisonEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=medisonEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property ChodziLezy() As DbSet(Of ChodziLezy)
    Public Property DaneLekarza() As DbSet(Of DaneLekarza)
    Public Property dtproperties() As DbSet(Of dtproperties)
    Public Property Leki() As DbSet(Of Leki)
    Public Property OpisyRachunku() As DbSet(Of OpisyRachunku)
    Public Property PacBezNazwisk() As DbSet(Of PacBezNazwisk)
    Public Property Pacjenci() As DbSet(Of Pacjenci)
    Public Property Plcie() As DbSet(Of Plcie)
    Public Property Pokrewienstwo() As DbSet(Of Pokrewienstwo)
    Public Property Recepty() As DbSet(Of Recepty)
    Public Property Skierowania() As DbSet(Of Skierowania)
    Public Property StatystycznaKlasyfikacjaChorob() As DbSet(Of StatystycznaKlasyfikacjaChorob)
    Public Property sysdiagrams() As DbSet(Of sysdiagrams)
    Public Property SzabGrupy() As DbSet(Of SzabGrupy)
    Public Property Szablony() As DbSet(Of Szablony)
    Public Property Towary() As DbSet(Of Towary)
    Public Property TypyDokumentow() As DbSet(Of TypyDokumentow)
    Public Property UbezpieczonyW() As DbSet(Of UbezpieczonyW)
    Public Property Usg() As DbSet(Of Usg)
    Public Property Wizyty() As DbSet(Of Wizyty)
    Public Property WizytyPacBezNazwisk() As DbSet(Of WizytyPacBezNazwisk)
    Public Property Zaklady() As DbSet(Of Zaklady)
    Public Property Zaklady_Kopia() As DbSet(Of Zaklady_Kopia)
    Public Property Zaswiadczenia() As DbSet(Of Zaswiadczenia)
    Public Property Zdjecia() As DbSet(Of Zdjecia)
    Public Property Zdjecia_ar() As DbSet(Of Zdjecia_ar)
    Public Property SkierowaniaCele() As DbSet(Of SkierowaniaCele)
    Public Property SkierowaniaPoradnie() As DbSet(Of SkierowaniaPoradnie)
    Public Property CelSzablony() As DbSet(Of CelSzablony)
    Public Property Rachunki() As DbSet(Of Rachunki)

End Class
