'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OpisyRachunku
    Public Property NrOpisuRach As Long
    Public Property IDrachunku As Nullable(Of Long)
    Public Property NrTowaru As Nullable(Of Integer)
    Public Property NazwaTowaru As String
    Public Property ZwolnienieVAT As Nullable(Of Boolean)
    Public Property StawkaVAT As Nullable(Of Double)
    Public Property SWWKWiU As String
    Public Property JedMiary As String
    Public Property CenaNetto As Nullable(Of Decimal)
    Public Property Ilosc As Nullable(Of Double)
    Public Property WartoscNetto As Nullable(Of Decimal)
    Public Property WartoscVAT As Nullable(Of Decimal)
    Public Property WartoscBrutto As Nullable(Of Decimal)

    Public Overridable Property Towary As Towary
    Public Overridable Property Rachunki As Rachunki

End Class
