'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Pacjenci
    Public Property Nrp As Long
    Public Property Nazwisko As String
    Public Property Nazwisko2 As String
    Public Property Imie As String
    Public Property Imie2 As String
    Public Property Plec As String
    Public Property rodzina As String
    Public Property DataUrodzenia As Nullable(Of Date)
    Public Property DataUrodzeniaOsobyPodOp As Nullable(Of Date)
    Public Property Kod As String
    Public Property Miejscowosc As String
    Public Property Adres As String
    Public Property NrDomu As String
    Public Property NrLokalu As String
    Public Property Telefon As String
    Public Property NIP As String
    Public Property Pesel As String
    Public Property Dowod As String
    Public Property Paszport As String
    Public Property SymbolKasy As String
    Public Property NrUbezpieczonyW As Nullable(Of Integer)
    Public Property GrKrwi As String
    Public Property Rh As String
    Public Property NIPzakladu As String
    Public Property NazwaZakladuPracy As String
    Public Property KodZakladuPracy As String
    Public Property MiastoZakladuPracy As String
    Public Property AdresZakladuPracy As String
    Public Property Zawod As String
    Public Property UBEZP As String
    Public Property UWAGI As String
    Public Property DataWprowadzenia As Nullable(Of Date)
    Public Property PoczatekZwoln180 As Nullable(Of Date)
    Public Property Kiedy180dni As Nullable(Of Date)
    Public Property NrZakladuPac As Nullable(Of Integer)
    Public Property KasaChorych As String
    Public Property ReceptaUprawnienia As String
    Public Property ReceptaChorobyPrzewlekle As String

    Public Overridable Property UbezpieczonyW As UbezpieczonyW
    Public Overridable Property Zaklady As Zaklady
    Public Overridable Property Skierowania As ICollection(Of Skierowania) = New HashSet(Of Skierowania)
    Public Overridable Property Wizyty As ICollection(Of Wizyty) = New HashSet(Of Wizyty)
    Public Overridable Property Zaswiadczenia As ICollection(Of Zaswiadczenia) = New HashSet(Of Zaswiadczenia)
    Public Overridable Property Rachunki As ICollection(Of Rachunki) = New HashSet(Of Rachunki)

End Class
