'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Pokrewienstwo
    Public Property KodPokrew As Integer
    Public Property OpisPokrewienstwa As String

    Public Overridable Property Wizyty As ICollection(Of Wizyty) = New HashSet(Of Wizyty)

End Class
