'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Rachunki
    Public Property IDrachunku As Long
    Public Property Nrp As Nullable(Of Long)
    Public Property NrGabinetu As Nullable(Of Integer)
    Public Property Numerrachunku As Nullable(Of Integer)
    Public Property EndFixNrRachunku As String
    Public Property DataWystawienia As Nullable(Of Date)
    Public Property NaKogo As String
    Public Property NaKogoAdres As String
    Public Property NaKogoKod As String
    Public Property NaKogoNIP As String
    Public Property TypRachunku As String
    Public Property VAT As Nullable(Of Decimal)
    Public Property Netto As Nullable(Of Decimal)
    Public Property Brutto As Nullable(Of Decimal)
    Public Property Wystawil As String
    Public Property NazwaFV As String
    Public Property KodFV As String
    Public Property MiastoFV As String
    Public Property AdresFV As String
    Public Property TelefonFV As String
    Public Property KomorkaFV As String
    Public Property NIPFV As String
    Public Property BankFV As String
    Public Property NrKontaFV As String
    Public Property SposobZap As String
    Public Property Wplaty As Nullable(Of Decimal)

    Public Overridable Property OpisyRachunku As ICollection(Of OpisyRachunku) = New HashSet(Of OpisyRachunku)
    Public Overridable Property Pacjenci As Pacjenci

End Class
