'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Recepty
    Public Property NrRecepty As Long
    Public Property NrWizyty As Nullable(Of Long)
    Public Property NrLeku As Nullable(Of Integer)
    Public Property Ilosc As String
    Public Property Postac As String
    Public Property Dawkowanie As String
    Public Property Odplatnosc As String
    Public Property Uwagi As String
    Public Property Dawka As String
    Public Property indywidualna As Nullable(Of Boolean)
    Public Property ReceptaChorobyPrzewlekle As String

    Public Overridable Property Leki As Leki
    Public Overridable Property Wizyty As Wizyty

End Class
