'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SkierowaniaPoradnie
    Public Property idPoradni As Long
    Public Property NazwaPoradni As String

    Public Overridable Property SkierowaniaCele As ICollection(Of SkierowaniaCele) = New HashSet(Of SkierowaniaCele)

End Class
