'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Skierowania
    Public Property NrSkierow As Long
    Public Property Nrp As Nullable(Of Long)
    Public Property DataSkierow As Nullable(Of Date)
    Public Property Rozpoznanie As String
    Public Property Cel As String
    Public Property DoKogo As String
    Public Property xml As String

    Public Overridable Property Pacjenci As Pacjenci

End Class
