'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Szablony
    Public Property NrSzablonu As Long
    Public Property NrGabinetu As Nullable(Of Integer)
    Public Property NrRodzSzab As Nullable(Of Integer)
    Public Property Kolejnosc As Nullable(Of Integer)
    Public Property Skrot As String
    Public Property OpisSz As String
    Public Property NrGrSzablon As Nullable(Of Long)

    Public Overridable Property SzabGrupy As SzabGrupy

End Class
