'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SzabGrupy
    Public Property NrGrSzablon As Long
    Public Property GrupaSz As String

    Public Overridable Property Szablony As ICollection(Of Szablony) = New HashSet(Of Szablony)

End Class
