'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Towary
    Public Property NrTowaru As Integer
    Public Property IndeksT As String
    Public Property SWWKWiU As String
    Public Property Kategoria As String
    Public Property Nazwa As String
    Public Property Wymiary As String
    Public Property JedMiary As String
    Public Property CenaNettoZakup As Nullable(Of Decimal)
    Public Property CenaNettoSugerowana As Nullable(Of Decimal)
    Public Property StawkaVAT As Nullable(Of Double)
    Public Property ZwolnienieVAT As Nullable(Of Boolean)

    Public Overridable Property OpisyRachunku As ICollection(Of OpisyRachunku) = New HashSet(Of OpisyRachunku)

End Class
