'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UbezpieczonyW
    Public Property NrUbezpieczonyW As Integer
    Public Property OpisUbezpieczonyW As String

    Public Overridable Property Pacjenci As ICollection(Of Pacjenci) = New HashSet(Of Pacjenci)

End Class
