'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usg
    Public Property NrUsg As Integer
    Public Property CzyjeUsgSkrot As String
    Public Property CzyjeUsg As String
    Public Property KwotaUsg As Nullable(Of Decimal)

    Public Overridable Property Wizyty As ICollection(Of Wizyty) = New HashSet(Of Wizyty)

End Class
