'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class WizytyPacBezNazwisk
    Public Property NrWizyty As Integer
    Public Property Nrp As Nullable(Of Integer)
    Public Property DataWizyty As Nullable(Of Date)
    Public Property GodzWizyty As Nullable(Of Date)
    Public Property wszedl As Nullable(Of Date)
    Public Property wyszedl As Nullable(Of Date)
    Public Property Wplata As Nullable(Of Decimal)
    Public Property L4 As Nullable(Of Boolean)
    Public Property WystawionoDnia As Nullable(Of Date)
    Public Property ZwolnienieOd As Nullable(Of Date)
    Public Property ZwolnienieDo As Nullable(Of Date)
    Public Property ZwolnienieDni As Nullable(Of Integer)
    Public Property NrStatystycznyChoroby As String
    Public Property KodABC1 As String
    Public Property KodABC2 As String
    Public Property KodABC3 As String
    Public Property KodABC4 As String
    Public Property NrChodziLezy As Nullable(Of Integer)
    Public Property NrTypuDokumentu As Nullable(Of Integer)
    Public Property KodPokrewienstwa As String
    Public Property NrGabinetu As Nullable(Of Integer)
    Public Property ImieLekarza As String
    Public Property NazwiskoLekarza As String
    Public Property NrLekarza As Nullable(Of Integer)
    Public Property NIPLekarza As String
    Public Property Id As Nullable(Of Short)
    Public Property NIPzakladu As String
    Public Property NazwaZakladuPracy As String
    Public Property KodZakladuPracy As String
    Public Property MiastoZakladuPracy As String
    Public Property AdresZakladuPracy As String
    Public Property Wywiad As String
    Public Property Badania As String
    Public Property usg As String
    Public Property Rozpoznanie As String
    Public Property Zalecenia As String
    Public Property Uwagi As String
    Public Property TerazTen As Nullable(Of Boolean)
    Public Property CzyDrukowac As Nullable(Of Boolean)
    Public Property NrZakladuWiz As Nullable(Of Integer)

End Class
