'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Zaklady
    Public Property NrZakladu As Integer
    Public Property NazwaZakladuPracy As String
    Public Property KodZakladuPracy As String
    Public Property MiastoZakladuPracy As String
    Public Property AdresZakladuPracy As String
    Public Property bledny As Nullable(Of Boolean)
    Public Property NIPzakladu As String
    Public Property NIPzakladu_old As String

    Public Overridable Property Pacjenci As ICollection(Of Pacjenci) = New HashSet(Of Pacjenci)

End Class
