'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Zdjecia_ar
    Public Property NrZdj As Integer
    Public Property wybor As Nullable(Of Boolean)
    Public Property plikzdj As String
    Public Property opiszdj As String
    Public Property NrWizyty As Nullable(Of Integer)
    Public Property Data_ar As Nullable(Of Date)
    Public Property Typ_ar As String
    Public Property Kto As String
    Public Property Gdzie As String

End Class
