'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Zdjecia
    Public Property NrZdj As Integer
    Public Property wybor As Nullable(Of Boolean)
    Public Property plikzdj As String
    Public Property opiszdj As String
    Public Property NrWizyty As Nullable(Of Long)

    Public Overridable Property Wizyty As Wizyty

End Class
